import { readdir } from "node:fs/promises";
import { join, relative, sep } from "node:path";

/**
 * Turns the Vite output into a TypeScript module so `bun build --compile` can
 * carry the frontend inside a single binary. Regenerated on every build; see
 * `src/web/generated/bundle.d.ts` for the type the rest of the code sees.
 */
const WEB_DIST = "dist/web";
const OUTPUT = "src/web/generated/bundle.ts";

const files = (await readdir(WEB_DIST, { recursive: true, withFileTypes: true }))
  .filter((entry) => entry.isFile())
  .map((entry) => join(entry.parentPath, entry.name))
  .toSorted();

if (files.length === 0) {
  console.error(`No files under ${WEB_DIST}. Run \`bun run build:web\` first.`);
  process.exit(1);
}

/**
 * A static import of a remote module makes the whole app fail to evaluate when
 * that host is unreachable, which shows up as a blank page rather than a
 * missing feature. Remote code must be loaded through `import()` at the point
 * of use instead.
 */
const REMOTE_STATIC_IMPORT = /\bfrom\s*["']https?:/;

const decoder = new TextDecoder("utf-8", { fatal: true });
const entries = await Promise.all(
  files.map(async (file) => {
    const key = `/${relative(WEB_DIST, file).split(sep).join("/")}`;
    const bytes = await Bun.file(file).bytes();

    try {
      const content = decoder.decode(bytes);
      if (REMOTE_STATIC_IMPORT.test(content)) {
        console.error(`${key} statically imports a remote module; use a dynamic import.`);
        process.exit(1);
      }
      return `  ${JSON.stringify(key)}: ${JSON.stringify(content)},`;
    } catch {
      // The bundle is a string map, so a binary asset would be silently
      // corrupted. Vite is configured to inline assets as data URIs instead.
      console.error(`${key} is not UTF-8 text and cannot be embedded.`);
      process.exit(1);
    }
  }),
);

await Bun.write(
  OUTPUT,
  `// Generated by scripts/embed-web.ts. Do not edit.
export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`,
);

console.log(`Embedded ${files.length} files from ${WEB_DIST} into ${OUTPUT}`);
