import { readdir } from "node:fs/promises";
import { join, relative, sep } from "node:path";

/**
 * Turns the Vite output into a TypeScript module so `bun build --compile` can
 * carry the frontend inside a single binary. Regenerated on every build; see
 * `src/web/generated/bundle.d.ts` for the type the rest of the code sees.
 */
const WEB_DIST = "dist/web";
const OUTPUT = "src/web/generated/bundle.ts";

const files = (await readdir(WEB_DIST, { recursive: true, withFileTypes: true }))
  .filter((entry) => entry.isFile())
  .map((entry) => join(entry.parentPath, entry.name))
  .toSorted();

if (files.length === 0) {
  console.error(`No files under ${WEB_DIST}. Run \`bun run build:web\` first.`);
  process.exit(1);
}

/**
 * A static import of a remote module makes the whole app fail to evaluate when
 * that host is unreachable, which shows up as a blank page rather than a
 * missing feature. Remote code must be loaded through `import()` at the point
 * of use instead.
 */
const REMOTE_STATIC_IMPORT = /\bfrom\s*["']https?:/;

/**
 * Every page pays for the entry chunk and whatever it statically imports before
 * it renders anything, so a feature as large as Mermaid (3MB) has to stay
 * behind `import()`. It has leaked into that closure once already: grouping
 * Mermaid into a single chunk moved Vite's preload helper in there, and the
 * entry needs the helper, so it imported the whole of Mermaid to get it. The
 * budget is well above the shell (~450kB) and well below anything that pulls a
 * diagram or maths renderer along.
 */
const ENTRY_BUDGET_BYTES = 1_500_000;
const STATIC_IMPORT = /(?:\bfrom|\bimport)\s*["']([^"']+)["']/g;
const HTML_ENTRY = /<script[^>]*\btype="module"[^>]*\bsrc="([^"]+)"/;

const decoder = new TextDecoder("utf-8", { fatal: true });
const assets = new Map<string, { content: string; size: number }>();

function assertEntryWithinBudget(): void {
  const html = assets.get("/index.html");
  const entry = html?.content.match(HTML_ENTRY)?.[1];
  if (!entry) {
    console.error("No module entry script in /index.html; the Vite output looks wrong.");
    process.exit(1);
  }

  const closure = new Set<string>();
  const queue = [entry];
  let total = 0;

  for (let key = queue.pop(); key !== undefined; key = queue.pop()) {
    const asset = assets.get(key);
    if (!asset || closure.has(key)) {
      continue;
    }
    closure.add(key);
    total += asset.size;

    for (const [, specifier] of asset.content.matchAll(STATIC_IMPORT)) {
      if (specifier.startsWith(".")) {
        queue.push(new URL(specifier, `file://${key}`).pathname);
      }
    }
  }

  if (total > ENTRY_BUDGET_BYTES) {
    const chunks = [...closure].toSorted().join("\n  ");
    console.error(
      `The entry loads ${total} bytes statically, over the ${ENTRY_BUDGET_BYTES} budget:\n  ${chunks}`,
    );
    process.exit(1);
  }
}

await Promise.all(
  files.map(async (file) => {
    const key = `/${relative(WEB_DIST, file).split(sep).join("/")}`;
    const bytes = await Bun.file(file).bytes();

    try {
      const content = decoder.decode(bytes);
      if (REMOTE_STATIC_IMPORT.test(content)) {
        console.error(`${key} statically imports a remote module; use a dynamic import.`);
        process.exit(1);
      }
      assets.set(key, { content, size: bytes.byteLength });
    } catch {
      // The bundle is a string map, so a binary asset would be silently
      // corrupted. Vite is configured to inline assets as data URIs instead.
      console.error(`${key} is not UTF-8 text and cannot be embedded.`);
      process.exit(1);
    }
  }),
);

assertEntryWithinBudget();

const entries = [...assets]
  .toSorted(([a], [b]) => (a < b ? -1 : 1))
  .map(([key, { content }]) => `  ${JSON.stringify(key)}: ${JSON.stringify(content)},`);

await Bun.write(
  OUTPUT,
  `// Generated by scripts/embed-web.ts. Do not edit.
export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`,
);

console.log(`Embedded ${files.length} files from ${WEB_DIST} into ${OUTPUT}`);
